[package]
name = "uno"
version = "0.1.0"
authors = ["Brainium Studios LLC"]
edition = "2018"

[features]
default = []

[dependencies]
en = "0.1.1"
paste = "1.0.0"
serde = { version = "1.0.115", features = ["serde_derive"], optional = true }
thiserror = "1.0.20"
